const documents = [
  {
    images: [
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/sp-uso-obrigatorio-frente-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/sp-uso-obrigatorio-verso-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/sp-uso-obrigatorio-aplicacao-800.jpeg?raw=true',
    ],
    category: 'care',
    name: 'Shampoo Uso Obrigatório 300ml',
    reviews: 2,
    price: 139.99,
    discount: 0.27,
    description: 'High-quality shampoo that nourishes and revitalizes hair. Ideal for daily use.',
    stock: 20,
  },
  {
    images: [
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/co-uso-obrigatorio-plus-frent-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/co-uso-obrigatorio-plus-verso-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/co-uso-obrigatorio-plus-aplicacao-800.jpeg?raw=true',
    ],
    category: 'care',
    name: 'Condicionador Uso Obrigatório Plus+ 300ml',
    reviews: 3,
    price: 119.99,
    discount: 0,
    description: 'Conditioner for smooth and manageable hair. Perfect for all hair types.',
    stock: 23,
  },
  {
    images: [
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/mask-net-mask.png?raw=true',
    ],
    category: 'treatments',
    name: 'Net Mask 550g',
    reviews: 5,
    price: 299.99,
    discount: 0,
    description: 'Intensive hair mask for deep conditioning. Ideal for damaged hair.',
    stock: 55,
  },
  {
    images: [
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/rec-uso-obrigatorio-frent-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/rec-uso-obrigatorio-verso-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/rec-uso-obrigatorio-aplic-800.jpeg?raw=true',
    ],
    category: 'treatments',
    name: 'Uso Obrigatório 260ml',
    reviews: 11,
    price: 119.99,
    discount: 0.25,
    description: 'Essential treatment for hair repair. Suitable for all hair types.',
    stock: 43,
  },
  {
    images: [
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/oleo-illuminate-frente.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/oleo-illuminate-verso.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/rec-uso-obrigatorio-aplic-800.jpeg?raw=true',
    ],
    category: 'finishers',
    name: 'Illuminatte Oil 60ml',
    reviews: 5,
    price: 139.99,
    discount: 0,
    description: 'Lightweight oil for shine and softness. Perfect for all hair types.',
    stock: 65,
  },
  {
    images: [
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/kit-uso-obrigatorio-frente-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/kit-uso-obrigatorio-verso.jpeg?raw=true',
    ],
    category: 'kits',
    name: 'Kit Frizz Zero',
    reviews: 18,
    price: 389.97,
    discount: 0.05,
    description: 'Complete kit for frizz control and smooth hair. Ideal for all hair types.',
    stock: 20,
  },
  {
    images: [
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/fix-shine-frent-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/fix-shine-verso-800.jpeg?raw=true',
      'https://github.com/estacioFilho/projeto-loja-cosmetico/blob/main/assets/fix-shine-aplicacao-800.jpeg?raw=true',
    ],
    category: 'finishers',
    name: 'Shine Fix 450ml',
    reviews: 6,
    price: 149.99,
    discount: 0,
    description: 'Spray for shine and hold. Ideal for styling and finishing.',
    stock: 20,
  },
];

module.exports = documents;
